// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXavNQllvVFs0OAaH5ATUFfoNoQHP7F0M',
    appId: '1:321912808494:web:5d18ab18330ef7febbabbf',
    messagingSenderId: '321912808494',
    projectId: 'sspsnotification',
    authDomain: 'sspsnotification.firebaseapp.com',
    storageBucket: 'sspsnotification.appspot.com',
    measurementId: 'G-6J1MYCELZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfmGsDzKxrW9zQdiJm4eBR_mohrjNZGYY',
    appId: '1:321912808494:android:92f3a1a97e7f430cbbabbf',
    messagingSenderId: '321912808494',
    projectId: 'sspsnotification',
    storageBucket: 'sspsnotification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdU9-2i7FwgFhLwrHusmgquhdZysmGgFk',
    appId: '1:321912808494:ios:a199923ebb370d6ebbabbf',
    messagingSenderId: '321912808494',
    projectId: 'sspsnotification',
    storageBucket: 'sspsnotification.appspot.com',
    iosBundleId: 'com.example.sspsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdU9-2i7FwgFhLwrHusmgquhdZysmGgFk',
    appId: '1:321912808494:ios:d6e7619014163c1cbbabbf',
    messagingSenderId: '321912808494',
    projectId: 'sspsnotification',
    storageBucket: 'sspsnotification.appspot.com',
    iosBundleId: 'com.example.sspsApp.RunnerTests',
  );
}
